"""
Evaluation metrics loader — the UI's only source of evaluation numbers.

No page is allowed to hardcode an evaluation figure. Everything comes from the
Stage 8 artifact through here, and anything the artifact does not contain renders
as "not yet measured" rather than as a number.

This module also reports *provenance*: the Stage 8 runner falls back to a
deterministic template when Ollama is unreachable, and an artifact produced that
way is not a model benchmark. We detect that and say so, rather than presenting
template output as a result.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = REPO_ROOT / "stage8_evaluation_report.json"

NOT_MEASURED = "— not yet measured"


@dataclass
class ModelMetrics:
    """Per-model figures, each optional."""
    name: str
    scenarios: int | None = None
    mean_latency_s: float | None = None
    mean_tokens_per_s: float | None = None
    hallucination_rate: float | None = None
    hallucination_free_pct: float | None = None
    zero_treatment_violation_pct: float | None = None
    rubric_pct: float | None = None


@dataclass
class EvaluationMetrics:
    """The loaded Stage 8 artifact, plus what we can honestly say about it."""
    available: bool = False
    source_path: str = str(REPORT_PATH)
    generated_at: datetime | None = None
    scenarios_count: int | None = None
    held_out_seed: int | None = None
    kappa: float | None = None
    kappa_interpretation: str | None = None
    models: dict[str, ModelMetrics] = field(default_factory=dict)
    recommendation: str | None = None

    # Provenance
    narrative_source: str = "unknown"       # "model" | "template" | "unknown"
    provenance_note: str = ""
    trustworthy: bool = False               # safe to present as a model benchmark?

    def fmt_pct(self, value: float | None, digits: int = 1) -> str:
        return NOT_MEASURED if value is None else f"{value * 100:.{digits}f}%"

    def fmt_pct_raw(self, value: float | None, digits: int = 1) -> str:
        """For fields the artifact already stores as 0-100."""
        return NOT_MEASURED if value is None else f"{value:.{digits}f}%"

    def fmt_num(self, value: float | None, digits: int = 3, suffix: str = "") -> str:
        return NOT_MEASURED if value is None else f"{value:.{digits}f}{suffix}"


def _detect_provenance(raw: dict[str, Any]) -> tuple[str, str, bool]:
    """
    Decide whether the artifact's narratives came from a model or from the
    runner's offline template.

    An explicit `narrative_source` field wins. Failing that, the giveaway is that
    the offline path emits identical text for every model and hardcodes latency,
    so two models with byte-identical narratives were not separately evaluated.
    """
    benchmarks = raw.get("model_benchmarks", {}) or {}

    declared = {
        item.get("narrative_source")
        for bench in benchmarks.values()
        for item in bench.get("items", [])
        if item.get("narrative_source")
    }
    if declared == {"ollama"} or declared == {"model"}:
        return "model", "Narratives generated by the local model at evaluation time.", True
    if declared and declared <= {"template", "fallback"}:
        return (
            "template",
            "Artifact was produced by the runner's offline template path — no model was invoked.",
            False,
        )

    names = list(benchmarks)
    if len(names) >= 2:
        first = [i.get("narrative_summary", "") for i in benchmarks[names[0]].get("items", [])]
        second = [i.get("narrative_summary", "") for i in benchmarks[names[1]].get("items", [])]
        if first and first == second:
            return (
                "template",
                (
                    f"{names[0]} and {names[1]} returned byte-identical narratives across all "
                    "scenarios, which only happens on the runner's offline template path. "
                    "These figures do not compare the two models."
                ),
                False,
            )

    # A single model, or nothing conclusive.
    for bench in benchmarks.values():
        latencies = {i.get("latency_s") for i in bench.get("items", [])}
        if len(latencies) == 1 and latencies != {None}:
            return (
                "template",
                (
                    "Every scenario reports an identical latency, which indicates a hardcoded "
                    "fallback value rather than a measured generation."
                ),
                False,
            )

    return "unknown", "Provenance of this artifact could not be established.", False


def _model_metrics(name: str, bench: dict[str, Any]) -> ModelMetrics:
    return ModelMetrics(
        name=name,
        scenarios=bench.get("scenarios_evaluated"),
        mean_latency_s=bench.get("mean_latency_s"),
        mean_tokens_per_s=bench.get("mean_tokens_per_s"),
        hallucination_rate=bench.get("mean_hallucination_rate"),
        hallucination_free_pct=bench.get("hallucination_free_percentage"),
        zero_treatment_violation_pct=bench.get("zero_treatment_violation_rate"),
        rubric_pct=bench.get("overall_mean_rubric_pct"),
    )


def load_evaluation_metrics(path: Path | None = None) -> EvaluationMetrics:
    """Load the Stage 8 artifact. Never raises — an unreadable artifact is 'unavailable'."""
    target = Path(path) if path else REPORT_PATH

    try:
        raw = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return EvaluationMetrics(
            available=False,
            source_path=str(target),
            provenance_note="No Stage 8 evaluation artifact found. Run the evaluation to populate this panel.",
        )

    source, note, trustworthy = _detect_provenance(raw)
    agreement = raw.get("inter_rater_agreement", {}) or {}

    ts = raw.get("timestamp")
    generated = None
    if isinstance(ts, (int, float)):
        try:
            generated = datetime.fromtimestamp(ts)
        except (OverflowError, OSError, ValueError):
            generated = None

    return EvaluationMetrics(
        available=True,
        source_path=str(target),
        generated_at=generated,
        scenarios_count=raw.get("scenarios_count"),
        held_out_seed=raw.get("held_out_seed"),
        kappa=agreement.get("overall_total_kappa"),
        kappa_interpretation=agreement.get("interpretation"),
        models={n: _model_metrics(n, b) for n, b in (raw.get("model_benchmarks") or {}).items()},
        recommendation=raw.get("recommendation"),
        narrative_source=source,
        provenance_note=note,
        trustworthy=trustworthy,
    )


def scenario_hallucination_rate(metrics: EvaluationMetrics, patient_id: str,
                                model: str | None = None) -> float | None:
    """
    The measured hallucination rate for one patient's scenario, if this patient was
    part of the held-out evaluation cohort. Returns None otherwise — most patients
    on the ward were never evaluated, and the UI must say so rather than imply a
    verified result.
    """
    if not metrics.available or not metrics.trustworthy:
        return None

    try:
        raw = json.loads(Path(metrics.source_path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None

    for name, bench in (raw.get("model_benchmarks") or {}).items():
        if model and name != model:
            continue
        for item in bench.get("items", []):
            if item.get("patient_id") == patient_id:
                return item.get("hallucination_rate")
    return None
